<div id="all-domains">
    <div class="title">
        Nos domaines
    </div>
    <?php $domains = $this->getDomains(); ?>
    <?php foreach ($domains as $domain): ?>
        <?php $src = $domain->getImageUrl(); ?>
        <?php $name = $domain->getName(); ?>
        <?php $id = $domain->getId(); ?>
        <div class="domain">
            <div class="container">
                <img src="<?php echo Mage::getBaseUrl("media").'/domain/'.$src; ?>" alt="">
                <a class="name" target="_blank" href="<?php echo $this->helper('exam_domain/data')->getDomainUrl($domain); ?>">
                    <?php echo $name; ?>
                </a>
                <div class="products">
                    <?php $nbProducts = Mage::Helper("exam_domain")->getProductsByDomain($domain,true); ?>
                    <?php if ($nbProducts>1): ?>
                        (<?php echo $nbProducts;?> produits)
                    <?php else: ?>
                        (<?php echo $nbProducts;?> produit)
                    <?php endif; ?>
                </div>
                <a class="link button" target="_blank" href="<?php echo $this->helper('exam_domain/data')->getDomainUrl($domain); ?>">
                    Voir les produits
                </a>
            </div>
        </div>
    <?php endforeach; ?>
</div>

<div id="map-canvas"></div>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBYpkX0pUn5lR8RKW9mbu03Svrn3Mkfrus"></script>
<script>
    function initialize() {
        var mapOptions = {
            zoom: 5,
            center: new google.maps.LatLng(46.863936, 2.527399),
            mapTypeId: google.maps.MapTypeId.ROADMAP
        };
        var map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);


        <?php foreach ($domains as $domain): ?>
            var marker<?php echo $domain->getId(); ?> = new google.maps.Marker({
                position: new google.maps.LatLng(<?php echo $domain->getLongitude(); ?>,<?php echo $domain->getLatitude(); ?>),
                map: map,
                title: 'marker'
            });
            var infowindow<?php echo $domain->getId(); ?> = new google.maps.InfoWindow({
                content: "<B><?php echo $domain->getName(); ?></B>"
            });
            google.maps.event.addListener(marker<?php echo $domain->getId(); ?>, 'click', function() {
                infowindow<?php echo $domain->getId(); ?>.open(map,marker<?php echo $domain->getId(); ?>);
            });
            google.maps.event.addListener(map, "click", function(event) {
                infowindow<?php echo $domain->getId(); ?>.close();
            });
        <?php endforeach; ?>
    }

    google.maps.event.addDomListener(window, 'load', initialize);
</script>
